// <auto-generated />
using System;
using ListagemDeFornecedores.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListagemDeFornecedores.API.Migrations
{
    [DbContext(typeof(FornecedoresContext))]
    [Migration("20200226144209_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasColumnType("TEXT");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FornecedorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Fornecedores");

                    b.HasDiscriminator<string>("Tipo").HasValue("Fornecedor");
                });

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.FornecedorPF", b =>
                {
                    b.HasBaseType("ListagemDeFornecedores.API.Models.Fornecedor");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFornecedor")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.FornecedorPJ", b =>
                {
                    b.HasBaseType("ListagemDeFornecedores.API.Models.Fornecedor");

                    b.Property<int>("EmpresaFornecedorId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("EmpresaFornecedorId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.Fornecedor", b =>
                {
                    b.HasOne("ListagemDeFornecedores.API.Models.Empresa", "Empresa")
                        .WithMany("Fornecedores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListagemDeFornecedores.API.Models.FornecedorPJ", b =>
                {
                    b.HasOne("ListagemDeFornecedores.API.Models.Empresa", "EmpresaFornecedor")
                        .WithOne("fornecedorPJ")
                        .HasForeignKey("ListagemDeFornecedores.API.Models.FornecedorPJ", "EmpresaFornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
